
server:
  port: 8086
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    #配置在日志中打印出执行的 SQL 语句信息。
    #show-sql: true
  datasource:
    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:mysql://**:3306/bmitest2?serverTimezone=Asia/Shanghai&useSSL=false&rewriteBatchedStatements=true&useCursorFetch=true
    username: root
    password: 23423423

logging:
  level:
    root: info

